---
- name: Install Jenkins
  homebrew:
    name: jenkins-lts
    state: present

- name: Start Jenkins Controller
  shell: |
    nohup /opt/homebrew/opt/openjdk@21/bin/java -Dmail.smtp.starttls.enable=true -jar /opt/homebrew/opt/jenkins-lts/libexec/jenkins.war --httpListenAddress=127.0.0.1 --httpPort=8080 -Djenkins.install.runSetupWizard=false > /tmp/jenkins.log 2>&1 &
  become: true
  become_user: moleksiienko
  async: 60
  poll: 0
  ignore_errors: true

- name: Wait for Jenkins to start
  ansible.builtin.wait_for:
    port: 8080
    state: started
    delay: 15
    timeout: 60

- name: Start Jenkins agent
  shell: |
    nohup curl -sO {{ jenkins_url }}/jnlpJars/agent.jar; java -jar agent.jar -url {{ jenkins_url }} -secret {{ jenkins_agent_secret }} -name agent1 -webSocket -workDir "{{ jenkins_agent_dir }}" > /tmp/jenkins-agent.log 2>&1 &
  args:
  become: true
  become_user: moleksiienko
  async: 60
  poll: 0
